### ISSUE TITLE
Exon ordering

### ISSUE THREAD

**Issue by fairliereese** [diekhans/gencode-backmap#3]
Hi Mark, funny meeting you here! I am troubleshooting my own software that breaks when a lifted-over GENCODE GTF is used (which is generated using this software). I think I've determined the cause of the issue being that the order of the exons for minus strand transcripts is opposite of what is seen in the normal GENCODE annotation GTFs. Is this intentional? 

You can see the full details of the issue in the issue on my repo:
https://github.com/mortazavilab/swan_vis/issues/5#issuecomment-647027841

**Comment by diekhans** [comment]
oh, so sorry that I didn't see this ticket :-(

yes, this was a bug that has been fixed.
